name:                mnist
version:             0.1.0.0
github:              "jared-w/mnist"
license:             BSD3
author:              "Jared Weakly"
maintainer:          "jweakly@pdx.edu"
copyright:           "Copyright: (c) 2017 Jared Weakly"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/jared-w/mnist#readme>

dependencies:
- base >= 4.7 && < 5
- mnist-idx
- vector
- hmatrix
- MonadRandom
# - hmatrix-morpheus
# - massiv
# - massiv-io

library:
  source-dirs: src

executables:
  mnist-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -O3
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    # - -fllvm
    dependencies:
    - mnist

tests:
  mnist-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mnist
